### ISSUE TITLE
[info request] PUK Details

### ISSUE THREAD

**Issue by abradshaw** [Toporin/Seedkeeper-Applet#4]
When using DIY  cards, if you enter the PIN wrong enough times you are prompted for the PUK - where can this be found/set?

**Comment by Toporin** [comment]
The SeedKeeper applet (and also Satochip) supports PUK code in case the card is blocked (too many wrong PIN). The PUK is configured during setup (see https://github.com/Toporin/Seedkeeper-Applet/blob/5716760bc09989c36a178a1d376554adce8e4d3b/src/org/seedkeeper/applet/SeedKeeper.java#L812C15-L812C25). 

 However, in practice PUK is not user friendly and add complexity to the setup as the user has to backup another sensitive info.
 
 So in practice in the SeedKeeperTool and other applications that uses Satochip/SeedKeeper, the PUK is usually set to a random value during setup, and not shown to user.

**Comment by abradshaw** [comment]
Thanks for the clarification
